### ISSUE TITLE
Missing index on the `deleted_at` field

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/go-utils#12]
Wow how could you forget such a basic feature...

:heart:  @Soulou

**Comment by EtienneM** [comment]
We actually don't setup indices in go-utils but in the project using it, don't we?

**Comment by johnsudaar** [comment]
Hmmm i usually like to setup indices in the project using such indices. Here we're using this field to get all Active members of a collection.

**Comment by Soulou** [comment]
@johnsudaar how do you want to handle this in a library like go-utils/mongo ?

**Comment by EtienneM** [comment]
Mmmm OK, but in such case, where would you add the code? I mean an `init` function sounds like a bad idea

**Comment by johnsudaar** [comment]
I would put this in the `mongo/document` library. And we could have something like 
```
document.Init(
    Model1,
    Model2,
    Model3,
)
```

Which will create indices if the document uses paranoid.

**Comment by Soulou** [comment]
`Init` is not the best name, it could be `EnsureParanoidIndices` ?
