### ISSUE TITLE
When adding a condition, automatically add surrounding quotes if needed

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/go-utils#29]
Where, And and Or methods

The call `query.And("status_code", influx.Equal, "'"+a.Metric+"'")` should be `query.And("status_code", influx.Equal, a.Metric)`. Easier to read, less error prone

**Comment by johnsudaar** [comment]
Yep but you wont be' able to write `status_code = 2`.

**Comment by johnsudaar** [comment]
However we could add a method that will look like:
```
query.And("status_code", influx.Equal, influx.String(a.Metric))
```

**Comment by EtienneM** [comment]
Sounds like a good tradeoff.
