### ISSUE TITLE
[nsqconsumer] Should we automatically add noRetry if error is mgo.ErrNotFound

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/go-utils#74]
We have plenty of issues like this one (https://github.com/Scalingo/scalingo-acme-agent/issues/72) that could be solved by modifying the nsqconsumer to automatically not retry if the root cause of the error is mgo.ErrNotFound. Do you think it's a good idea?

**Comment by Soulou** [comment]
I don't think having a dependency to mgo in the nsqconsumer lib is a good thing

**Comment by EtienneM** [comment]
OK
