### ISSUE TITLE
[errors] Add a method like `RootCause`

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/go-utils#840]
With the release of `ErrCtx`, we deprecated `errors.RootCause`. But there are some cases where it could be useful to get the root error. Shouldn't we add again a method like `RootCause`?

**Comment by leo-scalingo** [comment]
No , we should not :-) 

`Is` and `As` are the way to go to match the stdlib: https://github.com/Scalingo/go-utils/blob/master/errors/cause.go#L12-L38

https://pkg.go.dev/errors#As
https://pkg.go.dev/errors#Is

**Comment by leo-scalingo** [comment]
Actually Deprecation comments are already there

**Comment by EtienneM** [comment]
Can you have a look at the PR linked to this issue? IMO there is a valid use case for such a method. I don't want to link here the PR as it's in a private repository but GitHub added a link in the timeline of this issue.

**Comment by leo-scalingo** [comment]
Done

**Comment by ipfaze** [comment]
Closing this issue as it seems not useful to have this kind of method.
